unit CxP409;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  StdCtrls, wwdblook, Mask, wwdbedit, Wwdbspin,Db, Buttons, ExtCtrls,
  ppEndUsr, ppProd, ppClass, ppReport, ppComm, ppRelatv, ppCache, ppDB,
  ppDBPipe, ppVar, ppBands, ppCtrls, ppPrnabl, Grids, Wwdbigrd, Wwdbgrid,
  Wwdatsrc, DBClient, wwclient, Wwkeycb, oaVariables;

type
  TFCuadroMensual = class(TForm)
    lblCia: TLabel;
    dblcCia: TwwDBLookupCombo;
    edtCia: TEdit;
    Label1: TLabel;
    dbeAno: TwwDBSpinEdit;
    GroupBox1: TGroupBox;
    rbClTodos: TRadioButton;
    rbClSelec: TRadioButton;
    bbtnSeleccionaClAux: TBitBtn;
    GroupBox2: TGroupBox;
    rbAuxTodos: TRadioButton;
    rbAuxSelec: TRadioButton;
    bbtnSeleccionaAux: TBitBtn;
    rgMonto: TRadioGroup;
    rgMoneda: TRadioGroup;
    bbtnOk: TBitBtn;
    bbtnCanc: TBitBtn;
    ppdbCuadroMensual: TppDBPipeline;
    pprCuadroMensual: TppReport;
		ppDesigner1: TppDesigner;
    pnlClAux: TPanel;
    dbgClAux: TwwDBGrid;
    dbgClAuxSelec: TwwDBGrid;
    cdsClAux: TwwClientDataSet;
    dsClAux: TwwDataSource;
    dsClAuxClone: TwwDataSource;
		cdsClAuxClone: TwwClientDataSet;
		StaticText2: TStaticText;
		StaticText1: TStaticText;
		bbtnClAux: TBitBtn;
		pnlBusca: TPanel;
		lblBusca: TLabel;
		isBusca: TwwIncrementalSearch;
    cdsAux: TwwClientDataSet;
    dsAux: TwwDataSource;
    dsAuxClone: TwwDataSource;
    cdsAuxClone: TwwClientDataSet;
    pnlAux: TPanel;
    dbgAux: TwwDBGrid;
    dbgAuxSelec: TwwDBGrid;
    StaticText3: TStaticText;
    StaticText4: TStaticText;
    bbtnAux: TBitBtn;
    pnlBusca1: TPanel;
    lblBusca1: TLabel;
    isBusca1: TwwIncrementalSearch;
    ppHeaderBand1: TppHeaderBand;
    ppLabel1: TppLabel;
    pplblCCMAno: TppLabel;
    pplblCCMMoneda: TppLabel;
    ppLabel4: TppLabel;
    ppLabel5: TppLabel;
    ppLabel6: TppLabel;
    ppLabel7: TppLabel;
    ppLabel8: TppLabel;
    ppLabel9: TppLabel;
    ppLabel10: TppLabel;
    ppLabel11: TppLabel;
    ppLabel12: TppLabel;
    ppLabel13: TppLabel;
    ppLabel14: TppLabel;
    ppLabel15: TppLabel;
    ppLabel16: TppLabel;
    ppLabel17: TppLabel;
    ppLabel18: TppLabel;
    ppLabel19: TppLabel;
    pplblCCMCia: TppLabel;
    ppSystemVariable1: TppSystemVariable;
    ppSystemVariable2: TppSystemVariable;
    ppDetailBand1: TppDetailBand;
    ppDBCalc1: TppDBCalc;
    ppDBText1: TppDBText;
    ppdbENE: TppDBText;
    ppdbFEB: TppDBText;
    ppdbMAR: TppDBText;
    ppdbABR: TppDBText;
    ppdbMAY: TppDBText;
    ppdbJUN: TppDBText;
    ppdbJUL: TppDBText;
    ppdbAGO: TppDBText;
    ppdbSET: TppDBText;
    ppdbOCT: TppDBText;
    ppdbNOV: TppDBText;
    ppdbDIC: TppDBText;
    ppdbTOT: TppDBText;
    ppdbPOR: TppDBText;
    ppFooterBand1: TppFooterBand;
    ppSummaryBand1: TppSummaryBand;
    ppLabel2: TppLabel;
    ppdbTENE: TppDBCalc;
    ppdbTFEB: TppDBCalc;
    ppdbTMAR: TppDBCalc;
    ppdbTABR: TppDBCalc;
    ppdbTMAY: TppDBCalc;
    ppdbTJUN: TppDBCalc;
    ppdbTJUL: TppDBCalc;
    ppdbTAGO: TppDBCalc;
    ppdbTSET: TppDBCalc;
    ppdbTOCT: TppDBCalc;
    ppdbTNOV: TppDBCalc;
    ppdbTDIC: TppDBCalc;
    ppdbTTOT: TppDBCalc;
    ppdbTPOR: TppDBCalc;
    ppLabel3: TppLabel;
		procedure dblcCiaExit(Sender: TObject);
		procedure NotInList(Sender: TObject; LookupTable: TDataSet;	NewValue: String; var Accept: Boolean);
		procedure FormKeyPress(Sender: TObject; var Key: Char);
		procedure FormShow(Sender: TObject);
		procedure rbClTodosClick(Sender: TObject);
		procedure rbClSelecClick(Sender: TObject);
		procedure rbAuxTodosClick(Sender: TObject);
		procedure rbAuxSelecClick(Sender: TObject);
		procedure bbtnOkClick(Sender: TObject);
		procedure bbtnClAuxClick(Sender: TObject);
		procedure bbtnSeleccionaClAuxClick(Sender: TObject);
		procedure dbgClAuxSelecDragOver(Sender, Source: TObject; X, Y: Integer; State: TDragState; var Accept: Boolean);
		procedure dbgClAuxDragOver(Sender, Source: TObject; X, Y: Integer; State: TDragState; var Accept: Boolean);
		procedure dbgClAuxMouseDown(Sender: TObject; Button: TMouseButton; Shift: TShiftState; X, Y: Integer);
		procedure dbgClAuxSelecMouseDown(Sender: TObject; Button: TMouseButton; Shift: TShiftState; X, Y: Integer);
		procedure dbgClAuxTitleButtonClick(Sender: TObject; AFieldName: String);
		procedure dbgClAuxEndDrag(Sender, Target: TObject; X, Y: Integer);
    procedure bbtnAuxClick(Sender: TObject);
    procedure bbtnSeleccionaAuxClick(Sender: TObject);
    procedure dbgAuxDragOver(Sender, Source: TObject; X, Y: Integer;
      State: TDragState; var Accept: Boolean);
    procedure dbgAuxEndDrag(Sender, Target: TObject; X, Y: Integer);
    procedure dbgAuxMouseDown(Sender: TObject; Button: TMouseButton;
      Shift: TShiftState; X, Y: Integer);
    procedure dbgAuxSelecMouseDown(Sender: TObject; Button: TMouseButton;
      Shift: TShiftState; X, Y: Integer);
    procedure dbgAuxSelecDragOver(Sender, Source: TObject; X, Y: Integer;
      State: TDragState; var Accept: Boolean);
    procedure dbgAuxTitleButtonClick(Sender: TObject; AFieldName: String);
    procedure isBusca1Exit(Sender: TObject);
    procedure isBuscaExit(Sender: TObject);
    procedure dbgAuxSelecEndDrag(Sender, Target: TObject; X, Y: Integer);
    procedure dbgClAuxSelecEndDrag(Sender, Target: TObject; X, Y: Integer);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure FormCreate(Sender: TObject);
	private
		{ Private declarations }
	  procedure Centra;
    procedure CargaDataSource;
	public
		{ Public declarations }
	end;

  procedure OPComprasMensuales; stdcall;

exports
  OPComprasMensuales;

var
	FCuadroMensual: TFCuadroMensual;

implementation

uses CxPDM;

{$R *.DFM}


procedure OPComprasMensuales;
begin
   if DMCXP=nil then exit;
   if not DMCXP.DCOM1.Connected then Exit;
   if FVariables.w_Num_Formas>FVariables.w_Max_Formas then
   begin
      ShowMessage('No puede Invocar a más de '+Trim(IntToStr(FVariables.w_Max_Formas))+' opciones al mismo tiempo' );
      Exit;
   end;
   if Assigned( FCuadroMensual ) then Exit;
   try
     Screen.Cursor:=crHourGlass;
     FCuadroMensual:=TFCuadroMensual.Create( Application );
     FCuadroMensual.ActiveMDIChild;
     FVariables.w_Num_Formas :=FVariables.w_Num_Formas+1;
     Screen.Cursor:=crDefault;
   finally
   end;
end;


procedure TFCuadroMensual.dblcCiaExit(Sender: TObject);
begin
	 edtCia.Text:=DMCXP.DisplayDescrip('TGE101','CIADES','CiaID',dblcCia.Text);
	 if length(edtCia.Text)=0 then
	 begin
			ShowMessage('Falta Código de Compañía');
			dblcCia.SetFocus;
	 end;
end;

procedure TFCuadroMensual.NotInList(Sender: TObject; LookupTable: TDataSet;
  NewValue: String; var Accept: Boolean);
begin
  if TwwDBCustomLookupCombo(Sender).Text = '' then Accept := True;
  Accept := LookupTable.Locate(TwwDBCustomLookupCombo(Sender).LookUpField,NewValue,[]);
	if not Accept then
		TwwDBCustomLookupCombo(Sender).DropDown;
end;

procedure TFCuadroMensual.FormKeyPress(Sender: TObject; var Key: Char);
begin
   if key=#13 then begin
      key:=#0;
      perform(CM_DialogKey,VK_TAB,0);
   end;
end;

procedure TFCuadroMensual.FormShow(Sender: TObject);
var a,m,d:word;
begin
   DMCXP.AccesosUsuarios( DMCXP.wModulo,DMCXP.wUsuario,'2',Screen.ActiveForm.Name );
   
   DecodeDate(DateS,a,m,d);
 	 dbeAno.Value:=a;
   DMCXP.cdsReporte.Filter:='';
   DMCXP.cdsReporte.Filtered:=False;
   DMCXP.cdsReporte.IndexFieldNames:='';
end;

procedure TFCuadroMensual.rbClTodosClick(Sender: TObject);
begin
	rbClSelec.Checked:=False;
	bbtnSeleccionaClAux.Enabled:=False;
end;

procedure TFCuadroMensual.rbClSelecClick(Sender: TObject);
begin
	rbClTodos.Checked:=False;
	bbtnSeleccionaClAux.Enabled:=True;
end;

procedure TFCuadroMensual.rbAuxTodosClick(Sender: TObject);
begin
	rbAuxSelec.Checked:=False;
	bbtnSeleccionaAux.enabled:=False; 
end;

procedure TFCuadroMensual.rbAuxSelecClick(Sender: TObject);
begin
	rbAuxTodos.Checked:=False;
	bbtnSeleccionaAux.enabled:=True;
end;

procedure TFCuadroMensual.bbtnOkClick(Sender: TObject);
var
   sRCompras, sSQL, sSQL1, sSQL2, sSQL3, sSQL4, sSQL5, sSQL6 : string;
   sVar,sCadClAux,sCadAux,xDiarios:string;
   dTotal:double;
begin
   Screen.Cursor:=crHourGlass;
   sCadClAux:='';
   sSQL := 'Select TDIARID from TGE104 where REGISTRO=''C'' ';
   DMCXP.cdsQry2.Close;
   DMCXP.cdsQry2.IndexFieldNames:='';
   DMCXP.cdsQry2.Filter:='';
   DMCXP.cdsQry2.Filtered:=False;
   DMCXP.cdsQry2.datarequest(sSQL);
   DMCXP.cdsQry2.Open;
   xDiarios := '';
   while not DMCXP.cdsQry2.EOF do
   begin
      if xDiarios='' then
         xDiarios := quotedstr(DMCXP.cdsQry2.FieldByName('TDIARID').AsString)
      else
         xDiarios := xDiarios+','+quotedstr(DMCXP.cdsQry2.FieldByName('TDIARID').AsString);
      DMCXP.cdsQry2.Next;
   end;

// sRCompras:=DMCXP.DisplayDescrip('TGE104','TDIARID','REGISTRO','C');
   if rbClSelec.checked then
      if cdsClAuxClone.Active then
      begin
         cdsClAuxClone.First;
         while not cdsClAuxClone.EOF do
         begin
	    if cdsClAuxClone.RecordCount=1 then
	    begin
	    	sCadClAux:=sCadClAux+' CLAUXID='+QuotedStr(cdsClAuxClone.FieldByName('CLAUXID').AsString);
	    end
	    else
	    begin
	    	if cdsClAuxClone.RecordCount>1 then
	    	begin
	    	   if cdsClAuxClone.RecNo=cdsClAuxClone.RecordCount then
	    	      sCadClAux:=sCadClAux+' CLAUXID='+QuotedStr(cdsClAuxClone.FieldByName('CLAUXID').AsString)
	    	   else
	    	      sCadClAux:=sCadClAux+' CLAUXID='+QuotedStr(cdsClAuxClone.FieldByName('CLAUXID').AsString)+' OR ';
	    	end;
	    end;
	    cdsClAuxClone.Next;
	 end;

	 if Length(sCadClAux)>0 then
	    sCadClAux:='('+sCadClAux+')';
      end;

      sCadAux:='';
      if rbAuxSelec.checked then
         if cdsAuxClone.Active then
	 begin
		cdsAuxClone.First;
		while not cdsAuxClone.EOF do
		begin
			if cdsAuxClone.RecordCount=1 then
			begin
				sCadAux:=sCadAux+' PROV='+QuotedStr(cdsAuxClone.FieldByName('PROV').AsString);
			end
			else
			begin
				if cdsAuxClone.RecordCount>1 then
				begin
					if cdsAuxClone.RecNo=cdsAuxClone.RecordCount then
						sCadAux:=sCadAux+' PROV='+QuotedStr(cdsAuxClone.FieldByName('PROV').AsString)
					else
						sCadAux:=sCadAux+' PROV='+QuotedStr(cdsAuxClone.FieldByName('PROV').AsString)+' OR ';
				end;
			end;
			cdsAuxClone.Next;
		end;

		if Length(sCadAux)>0 then
			sCadAux:='('+sCadAux+')';
      end;

      if (rgMonto.ItemIndex=2) AND (rgMoneda.ItemIndex=0) then
		sVar:='01';
      if (rgMonto.ItemIndex=2) AND (rgMoneda.ItemIndex=1) then
		sVar:='02';
      if (rgMonto.ItemIndex=0) AND (rgMoneda.ItemIndex=0) then
		sVar:='03';
      if (rgMonto.ItemIndex=0) AND (rgMoneda.ItemIndex=1) then
		sVar:='04';
      if (rgMonto.ItemIndex=1) AND (rgMoneda.ItemIndex=0) then
		sVar:='05';
      if (rgMonto.ItemIndex=1) AND (rgMoneda.ItemIndex=1) then
		sVar:='06';

      sSQL:='SELECT '+
	' PROVDES, '+
	' SUM(CP0101) CP0101,SUM(CP0102) CP0102,SUM(CP0103) CP0103,SUM(CP0104) CP0104,SUM(CP0105) CP0105,SUM(CP0106) CP0106, '+
	' SUM(CP0107) CP0107,SUM(CP0108) CP0108,SUM(CP0109) CP0109,SUM(CP0110) CP0110,SUM(CP0111) CP0111,SUM(CP0112) CP0112, '+
	' SUM(CP0113) CP0113, '+
	' '+
	' SUM(CP0201) CP0201,SUM(CP0202) CP0202,SUM(CP0203) CP0203,SUM(CP0204) CP0204,SUM(CP0205) CP0205,SUM(CP0206) CP0206, '+
	' SUM(CP0207) CP0207,SUM(CP0208) CP0208,SUM(CP0209) CP0209,SUM(CP0210) CP0210,SUM(CP0211) CP0211,SUM(CP0212) CP0212, '+
	' SUM(CP0213) CP0213, '+
	' '+
	' SUM(CP0301) CP0301,SUM(CP0302) CP0302,SUM(CP0303) CP0303,SUM(CP0304) CP0304,SUM(CP0305) CP0305,SUM(CP0306) CP0306, '+
	' SUM(CP0307) CP0307,SUM(CP0308) CP0308,SUM(CP0309) CP0309,SUM(CP0310) CP0310,SUM(CP0311) CP0311,SUM(CP0312) CP0312, '+
	' SUM(CP0313) CP0313, '+
	' '+
	' SUM(CP0401) CP0401,SUM(CP0402) CP0402,SUM(CP0403) CP0403,SUM(CP0404) CP0404,SUM(CP0405) CP0405,SUM(CP0406) CP0406, '+
	' SUM(CP0407) CP0407,SUM(CP0408) CP0408,SUM(CP0409) CP0409,SUM(CP0410) CP0410,SUM(CP0411) CP0411,SUM(CP0412) CP0412, '+
	' SUM(CP0413) CP0413, '+
	' '+
	' SUM(CP0501) CP0501,SUM(CP0502) CP0502,SUM(CP0503) CP0503,SUM(CP0504) CP0504,SUM(CP0505) CP0505,SUM(CP0506) CP0506, '+
	' SUM(CP0507) CP0507,SUM(CP0508) CP0508,SUM(CP0509) CP0509,SUM(CP0510) CP0510,SUM(CP0511) CP0511,SUM(CP0512) CP0512, '+
	' SUM(CP0513) CP0513, '+
	' '+
	' SUM(CP0601) CP0601,SUM(CP0602) CP0602,SUM(CP0603) CP0603,SUM(CP0604) CP0604,SUM(CP0605) CP0605,SUM(CP0606) CP0606, '+
	' SUM(CP0607) CP0607,SUM(CP0608) CP0608,SUM(CP0609) CP0609,SUM(CP0610) CP0610,SUM(CP0611) CP0611,SUM(CP0612) CP0612, '+
	' SUM(CP0613) CP0613, '+
	' '+
	' 0.000 PORC '+
	' FROM ( ';

     if (SRV_D = 'DB2NT') or (SRV_D = 'DB2400') then
     begin
     sSQL1:=
	'SELECT '
       +  'PROVDES, '
       +  'CASE WHEN MONTH(CPFEMIS)=01 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0101, '
       +  'CASE WHEN MONTH(CPFEMIS)=02 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0102, '
       +  'CASE WHEN MONTH(CPFEMIS)=03 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0103, '
       +  'CASE WHEN MONTH(CPFEMIS)=04 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0104, '
       +  'CASE WHEN MONTH(CPFEMIS)=05 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0105, '
       +  'CASE WHEN MONTH(CPFEMIS)=06 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0106, '
       +  'CASE WHEN MONTH(CPFEMIS)=07 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0107, '
       +  'CASE WHEN MONTH(CPFEMIS)=08 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0108, '
       +  'CASE WHEN MONTH(CPFEMIS)=09 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0109, '
       +  'CASE WHEN MONTH(CPFEMIS)=10 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0110, '
       +  'CASE WHEN MONTH(CPFEMIS)=11 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0111, '
       +  'CASE WHEN MONTH(CPFEMIS)=12 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0112, '
       +                                   'SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) CP0113, '
       +  ' '
       +  'CASE WHEN MONTH(CPFEMIS)=01 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0201, '
       +  'CASE WHEN MONTH(CPFEMIS)=02 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0202, '
       +  'CASE WHEN MONTH(CPFEMIS)=03 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0203, '
       +  'CASE WHEN MONTH(CPFEMIS)=04 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0204, '
       +  'CASE WHEN MONTH(CPFEMIS)=05 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0205, '
       +  'CASE WHEN MONTH(CPFEMIS)=06 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0206, '
       +  'CASE WHEN MONTH(CPFEMIS)=07 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0207, '
       +  'CASE WHEN MONTH(CPFEMIS)=08 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0208, '
       +  'CASE WHEN MONTH(CPFEMIS)=09 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0209, '
       +  'CASE WHEN MONTH(CPFEMIS)=10 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0210, '
       +  'CASE WHEN MONTH(CPFEMIS)=11 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0211, '
       +  'CASE WHEN MONTH(CPFEMIS)=12 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0212, '
       +                                   'SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) CP0213, '
       +  ' ';

     sSQL2:=
          'CASE WHEN MONTH(CPFEMIS)=01 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0301, '
       +  'CASE WHEN MONTH(CPFEMIS)=02 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0302, '
       +  'CASE WHEN MONTH(CPFEMIS)=03 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0303, '
       +  'CASE WHEN MONTH(CPFEMIS)=04 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0304, '
       +  'CASE WHEN MONTH(CPFEMIS)=05 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0305, '
       +  'CASE WHEN MONTH(CPFEMIS)=06 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0306, '
       +  'CASE WHEN MONTH(CPFEMIS)=07 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0307, '
       +  'CASE WHEN MONTH(CPFEMIS)=08 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0308, '
       +  'CASE WHEN MONTH(CPFEMIS)=09 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0309, '
       +  'CASE WHEN MONTH(CPFEMIS)=10 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0310, '
       +  'CASE WHEN MONTH(CPFEMIS)=11 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0311, '
       +  'CASE WHEN MONTH(CPFEMIS)=12 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0312, '
       +                                   'SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*CPTCAMPR,3) END END) CP0313, '
       +  ' ';

     sSQL3:=
          'CASE WHEN MONTH(CPFEMIS)=01 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0401, '
       +  'CASE WHEN MONTH(CPFEMIS)=02 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0402, '
       +  'CASE WHEN MONTH(CPFEMIS)=03 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0403, '
       +  'CASE WHEN MONTH(CPFEMIS)=04 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0404, '
       +  'CASE WHEN MONTH(CPFEMIS)=05 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0405, '
       +  'CASE WHEN MONTH(CPFEMIS)=06 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0406, '
       +  'CASE WHEN MONTH(CPFEMIS)=07 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0407, '
       +  'CASE WHEN MONTH(CPFEMIS)=08 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0408, '
       +  'CASE WHEN MONTH(CPFEMIS)=09 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0409, '
       +  'CASE WHEN MONTH(CPFEMIS)=10 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0410, '
       +  'CASE WHEN MONTH(CPFEMIS)=11 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0411, '
       +  'CASE WHEN MONTH(CPFEMIS)=12 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0412, '
       +                                   'SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1 ELSE ROUND(((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0)) ELSE ROUND((COALESCE(CPGRAVAD,0)+COALESCE(CPGRAVAD2,0))/CPTCAMPR,3) END END) CP0413, '
       +  ' ';

     sSQL4:=
          'CASE WHEN MONTH(CPFEMIS)=01 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0501, '
       +  'CASE WHEN MONTH(CPFEMIS)=02 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0502, '
       +  'CASE WHEN MONTH(CPFEMIS)=03 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0503, '
       +  'CASE WHEN MONTH(CPFEMIS)=04 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0504, '
       +  'CASE WHEN MONTH(CPFEMIS)=05 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0505, '
       +  'CASE WHEN MONTH(CPFEMIS)=06 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0506, '
       +  'CASE WHEN MONTH(CPFEMIS)=07 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0507, '
       +  'CASE WHEN MONTH(CPFEMIS)=08 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0508, '
       +  'CASE WHEN MONTH(CPFEMIS)=09 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0509, '
       +  'CASE WHEN MONTH(CPFEMIS)=10 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0510, '
       +  'CASE WHEN MONTH(CPFEMIS)=11 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0511, '
       +  'CASE WHEN MONTH(CPFEMIS)=12 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0512, '
       +                                   'SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*CPTCAMPR),3) END END) CP0513, '
       +  ' ';

     sSQL5:=
          'CASE WHEN MONTH(CPFEMIS)=01 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0601, '
       +  'CASE WHEN MONTH(CPFEMIS)=02 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0602, '
       +  'CASE WHEN MONTH(CPFEMIS)=03 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0603, '
       +  'CASE WHEN MONTH(CPFEMIS)=04 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0604, '
       +  'CASE WHEN MONTH(CPFEMIS)=05 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0605, '
       +  'CASE WHEN MONTH(CPFEMIS)=06 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0606, '
       +  'CASE WHEN MONTH(CPFEMIS)=07 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0607, '
       +  'CASE WHEN MONTH(CPFEMIS)=08 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0608, '
       +  'CASE WHEN MONTH(CPFEMIS)=09 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0609, '
       +  'CASE WHEN MONTH(CPFEMIS)=10 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0610, '
       +  'CASE WHEN MONTH(CPFEMIS)=11 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0611, '
       +  'CASE WHEN MONTH(CPFEMIS)=12 THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0612, '
       +                                   'SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(COALESCE(CPIGV,0)+COALESCE(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((COALESCE(CPIGV,0)+COALESCE(CPIGV2,0))/CPTCAMPR),3) END END) CP0613 '
       +  ' ';
   sSQL6:=
        'FROM CXP301, TGE110 '
       +'WHERE CIAID='+QuotedStr(dblcCia.text)+' AND CXP301.TDIARID in ('+xDiarios+') '
       +  'AND YEAR(CPFEMIS)='+dbeAno.text+' '
       +  'AND CXP301.DOCID=TGE110.DOCID AND TGE110.DOCMOD=''CXP'' ';

     if Length(sCadClAux)>0 then
	sSQL6:=sSQL6+' AND '+sCadClAux;
     if Length(sCadAux)>0 then
	sSQL6:=sSQL6+' AND '+sCadAux;

   sSQL6:=sSQL6+
          ' GROUP BY PROVDES,CPFEMIS '
	 +  ') X '
         +'WHERE CP'+sVar+'13 >0 '
         +'GROUP BY PROVDES ORDER BY CP'+sVar+'13 DESC ';
   END;

   if SRV_D = 'ORACLE' then
   begin
     sSQL1:=
	'SELECT '
       +  'PROVDES, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''01'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0101, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''02'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0102, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''03'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0103, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''04'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0104, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''05'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0105, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''06'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0106, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''07'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0107, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''08'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0108, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''09'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0109, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''10'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0110, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''11'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0111, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''12'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) ELSE 0 END CP0112, '
       +                                   'SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOLOC*-1 ELSE CPMTOLOC END) CP0113, '
       +  ' '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''01'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0201, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''02'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0202, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''03'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0203, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''04'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0204, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''05'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0205, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''06'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0206, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''07'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0207, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''08'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0208, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''09'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0209, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''10'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0210, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''11'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0211, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''12'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) ELSE 0 END CP0212, '
       +                                   'SUM(CASE WHEN DOCRESTA=''S'' THEN CPMTOEXT*-1 ELSE CPMTOEXT END) CP0213, '
       +  ' ';

     sSQL2:=
          'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''01'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0301, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''02'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0302, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''03'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0303, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''04'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0304, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''05'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0305, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''06'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0306, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''07'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0307, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''08'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0308, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''09'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0309, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''10'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0310, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''11'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0311, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''12'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*CPTCAMPR,3) END END) ELSE 0 END CP0312, '
       +                                   'SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)*CPTCAMPR,3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*CPTCAMPR,3) END END) CP0313, '
       +  ' ';

     sSQL3:=
          'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''01'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0401, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''02'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0402, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''03'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0403, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''04'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0404, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''05'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0405, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''06'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0406, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''07'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0407, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''08'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0408, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''09'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0409, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''10'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0410, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''11'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0411, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''12'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))/CPTCAMPR,3) END END) ELSE 0 END CP0412, '
       +                                   'SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1 ELSE ROUND(((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))*-1)/CPTCAMPR,3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0)) ELSE ROUND((NVL(CPGRAVAD,0)+NVL(CPGRAVAD2,0))/CPTCAMPR,3) END END) CP0413, '
       +  ' ';

     sSQL4:=
          'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''01'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((NVL(CPIGV,0)+NVL(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0501, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''02'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((NVL(CPIGV,0)+NVL(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0502, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''03'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((NVL(CPIGV,0)+NVL(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0503, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''04'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((NVL(CPIGV,0)+NVL(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0504, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''05'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((NVL(CPIGV,0)+NVL(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0505, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''06'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((NVL(CPIGV,0)+NVL(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0506, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''07'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((NVL(CPIGV,0)+NVL(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0507, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''08'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((NVL(CPIGV,0)+NVL(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0508, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''09'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((NVL(CPIGV,0)+NVL(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0509, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''10'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((NVL(CPIGV,0)+NVL(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0510, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''11'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((NVL(CPIGV,0)+NVL(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0511, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''12'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((NVL(CPIGV,0)+NVL(CPIGV2,0))*CPTCAMPR),3) END END) ELSE 0 END CP0512, '
       +                                   'SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOLOC-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)*CPTCAMPR),3) END ELSE CASE WHEN TMONID='+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOLOC-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOLOC-((NVL(CPIGV,0)+NVL(CPIGV2,0))*CPTCAMPR),3) END END) CP0513, '
       +  ' ';

     sSQL5:=
          'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''01'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((NVL(CPIGV,0)+NVL(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0601, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''02'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((NVL(CPIGV,0)+NVL(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0602, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''03'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((NVL(CPIGV,0)+NVL(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0603, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''04'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((NVL(CPIGV,0)+NVL(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0604, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''05'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((NVL(CPIGV,0)+NVL(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0605, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''06'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((NVL(CPIGV,0)+NVL(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0606, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''07'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((NVL(CPIGV,0)+NVL(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0607, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''08'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((NVL(CPIGV,0)+NVL(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0608, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''09'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((NVL(CPIGV,0)+NVL(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0609, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''10'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((NVL(CPIGV,0)+NVL(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0610, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''11'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((NVL(CPIGV,0)+NVL(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0611, '
       +  'CASE WHEN TO_CHAR(CPFEMIS,''MM'')=''12'' THEN SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((NVL(CPIGV,0)+NVL(CPIGV2,0))/CPTCAMPR),3) END END) ELSE 0 END CP0612, '
       +                                   'SUM(CASE WHEN DOCRESTA=''S'' THEN CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN (CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)))*-1 ELSE ROUND(CPMTOEXT-(((NVL(CPIGV,0)+NVL(CPIGV2,0))*-1)/CPTCAMPR),3) END ELSE CASE WHEN TMONID<>'+QuotedStr(DMCXP.wTMonLoc)+' THEN CPMTOEXT-(NVL(CPIGV,0)+NVL(CPIGV2,0)) ELSE ROUND(CPMTOEXT-((NVL(CPIGV,0)+NVL(CPIGV2,0))/CPTCAMPR),3) END END) CP0613 '
       +  ' ';
   sSQL6:=
        'FROM CXP301, TGE110 '
       +'WHERE CIAID='+QuotedStr(dblcCia.text)+' AND CXP301.TDIARID in ('+xDiarios+') '
       +  'AND TO_CHAR(CPFEMIS,''YYYY'')='''+dbeAno.text+''' '
       +  'AND CXP301.DOCID=TGE110.DOCID AND TGE110.DOCMOD=''CXP'' ';

     if Length(sCadClAux)>0 then
	sSQL6:=sSQL6+' AND '+sCadClAux;
     if Length(sCadAux)>0 then
	sSQL6:=sSQL6+' AND '+sCadAux;

   sSQL6:=sSQL6+
          ' GROUP BY PROVDES,CPFEMIS '
	 +  ') X '
         +'WHERE CP'+sVar+'13 >0 '
         +'GROUP BY PROVDES ORDER BY CP'+sVar+'13 DESC ';
   END;


   DMCXP.cdsReporte.Filter:='';
   DMCXP.cdsReporte.Filtered:=False;
   DMCXP.cdsReporte.IndexFieldNames:='';
   DMCXP.cdsReporte.Close;
   DMCXP.cdsReporte.DataRequest( sSQL + sSQL1 + sSQL2 + sSQL3 + sSQL4 + sSQL5 + sSQL6 );
   DMCXP.cdsReporte.Open;

	dTotal:=OperClientDataSet( DMCXP.cdsReporte , 'SUM(CP'+sVar+'13)', '');
	DMCXP.cdsReporte.First;
	while not DMCXP.cdsReporte.Eof do
	begin
		DMCXP.cdsReporte.Edit;
		DMCXP.cdsReporte.FieldByName('PORC').AsFloat:=FRound((DMCXP.cdsReporte.FieldByName('CP'+sVar+'13').AsFloat/dTotal)*100,15,5);
		DMCXP.cdsReporte.Post;
		DMCXP.cdsReporte.Next;
	end;
	DMCXP.cdsReporte.First;

	Screen.Cursor:=crDefault;

	if DMCXP.cdsReporte.RecordCount>0 then
	begin
		pprCuadroMensual.TEMPLATE.FileName:=ExtractFilePath( application.ExeName )+wRutaRpt+'\CuadroMensualCompras.rtm';
		pprCuadroMensual.template.LoadFromFile ;

		pplblCCMCia.caption:=edtCia.text;
		pplblCCMAno.caption:=dbeAno.text;

		if rgMoneda.itemindex=0 then
			pplblCCMMoneda.caption:='* '+DMCXP.DisplayDescrip('TGE103','TMONDES','TMON_LOC','L')+' *'
		else
      pplblCCMMoneda.caption:='* '+DMCXP.DisplayDescrip('TGE103','TMONDES','TMON_LOC','E')+' *';

		ppdbENE.DataField:='CP'+sVar+'01';
		ppdbFEB.DataField:='CP'+sVar+'02';
		ppdbMAR.DataField:='CP'+sVar+'03';
		ppdbABR.DataField:='CP'+sVar+'04';
		ppdbMAY.DataField:='CP'+sVar+'05';
		ppdbJUN.DataField:='CP'+sVar+'06';
		ppdbJUL.DataField:='CP'+sVar+'07';
		ppdbAGO.DataField:='CP'+sVar+'08';
		ppdbSET.DataField:='CP'+sVar+'09';
		ppdbOCT.DataField:='CP'+sVar+'10';
		ppdbNOV.DataField:='CP'+sVar+'11';
		ppdbDIC.DataField:='CP'+sVar+'12';
		ppdbTOT.DataField:='CP'+sVar+'13';

		ppdbTENE.DataField:='CP'+sVar+'01';
		ppdbTFEB.DataField:='CP'+sVar+'02';
		ppdbTMAR.DataField:='CP'+sVar+'03';
		ppdbTABR.DataField:='CP'+sVar+'04';
		ppdbTMAY.DataField:='CP'+sVar+'05';
		ppdbTJUN.DataField:='CP'+sVar+'06';
		ppdbTJUL.DataField:='CP'+sVar+'07';
		ppdbTAGO.DataField:='CP'+sVar+'08';
		ppdbTSET.DataField:='CP'+sVar+'09';
		ppdbTOCT.DataField:='CP'+sVar+'10';
		ppdbTNOV.DataField:='CP'+sVar+'11';
		ppdbTDIC.DataField:='CP'+sVar+'12';
		ppdbTTOT.DataField:='CP'+sVar+'13';

	//	ppDesigner1.Show;
		pprCuadroMensual.Print;
	end
	else
	begin
		ShowMessage('No existen Registros que mostrar');
	end;

end;

procedure TFCuadroMensual.bbtnClAuxClick(Sender: TObject);
begin
	pnlClAux.Visible:=False;
	FCuadroMensual.Width:=218;
  Centra;	
end;

procedure TFCuadroMensual.bbtnSeleccionaClAuxClick(Sender: TObject);
var
	xSQL:string;
begin
	Screen.Cursor:=crHourGlass;
	pnlClAux.Visible:=True;
	pnlClAux.BringToFront;
	cdsClAux.Close;
	cdsClAux.RemoteServer := DMCXP.DCOM1 ;
	cdsClAux.ProviderName := 'dspTGE';

	xSQL:=' SELECT CLAUXID,CLAUXDES,''N'' FLAG FROM TGE102 WHERE CLAUXCP=''A'' OR CLAUXCP=''P'' ';

	cdsClAux.DataRequest(xSQL);
	cdsClAux.Open;
	cdsClAux.IndexFieldNames:='CLAUXID';

	dbgClAux.Selected.Clear;
	dbgClAux.Selected.Add('CLAUXID'#9'3'#9'Id'#9'T');
	dbgClAux.Selected.Add('CLAUXDES'#9'15'#9'Descripción'#9'T');
	dbgClAux.RedrawGrid;

	cdsClAuxClone.CloneCursor(cdsClAux,TRUE) ;
	cdsClAuxClone.FILTER := 'FLAG = ''S''' ;
	cdsClAuxClone.FILTERED := True ;
	dbgClAuxSelec.Selected.Clear;
	dbgClAuxSelec.Selected.Add('CLAUXID'#9'3'#9'Id'#9'T');
	dbgClAuxSelec.Selected.Add('CLAUXDES'#9'15'#9'Descripción'#9'T');
	dbgClAuxSelec.RedrawGrid;
	Screen.Cursor:=crDefault;
	FCuadroMensual.Width:=635;
	Centra;
end;

procedure TFCuadroMensual.dbgClAuxSelecDragOver(Sender, Source: TObject; X,
	Y: Integer; State: TDragState; var Accept: Boolean);
begin
	 Accept:=True;
end;

procedure TFCuadroMensual.dbgClAuxDragOver(Sender, Source: TObject; X,
  Y: Integer; State: TDragState; var Accept: Boolean);
begin
	 Accept:=True;
end;

procedure TFCuadroMensual.dbgClAuxMouseDown(Sender: TObject;
	Button: TMouseButton; Shift: TShiftState; X, Y: Integer);
begin
	 dbgClAux.BeginDrag(False);
end;

procedure TFCuadroMensual.dbgClAuxSelecMouseDown(Sender: TObject;
	Button: TMouseButton; Shift: TShiftState; X, Y: Integer);
begin
  dbgClAuxSelec.BeginDrag(False);
end;

procedure TFCuadroMensual.dbgClAuxTitleButtonClick(Sender: TObject;
  AFieldName: String);
begin
	 if AFieldName='CLAUXID'  then lblBusca.Caption:='Clase de Auxiliar:';
	 if AFieldName='CLAUXDES' then lblBusca.Caption:='Nombre de Clase de Auxiliar:';
	 cdsClAux.indexfieldNames:= AFieldName;
	 isBusca.SearchField:= AFieldName;
	 isBusca.Left := lblBusca.Width+24;
	 pnlBusca.Width:= 12+lblBusca.Width+12+isBusca.Width+12;
	 pnlBusca.Visible := True;
	 isBusca.SetFocus;
end;

procedure TFCuadroMensual.dbgClAuxEndDrag(Sender, Target: TObject; X,
	Y: Integer);
var i:integer;
begin
	 If (Target = dbgClAuxSelec) AND (cdsClAux.recordcount <> 0 ) Then
	 begin
			if dbgClAux.SelectedList.Count>0 then
			begin
				 for i:= 0 to dbgClAux.SelectedList.Count-1 do
				 begin
							dbgClAux.datasource.dataset.GotoBookmark(dbgClAux.SelectedList.items[i]);
							cdsClAux.edit ;
							cdsClAux.FieldByName('FLAG').AsString := 'S' ;
							cdsClAux.Post ;
							dbgClAux.datasource.dataset.Freebookmark(dbgClAux.SelectedList.items[i]);
				 end; // for
				 dbgClAux.SelectedList.clear;  { Clear selected record list since they are all deleted}
			end
			else
			begin
				 cdsClAux.edit ;
				 cdsClAux.FieldByName('FLAG').AsString := 'S' ;
				 cdsClAux.Post ;
			end;
	 end ;
end;

procedure TFCuadroMensual.bbtnAuxClick(Sender: TObject);
begin
	pnlAux.Visible:=False;
	FCuadroMensual.Width:=218;
	Centra;
end;

procedure TFCuadroMensual.bbtnSeleccionaAuxClick(Sender: TObject);
var
	xSQL,cad:string;
begin
	Screen.Cursor:=crHourGlass;
	cad:='';
	if cdsClAuxClone.Active then
	begin
		pnlAux.Visible:=True;
		pnlAux.BringToFront;
		cdsClAuxClone.First;
		while not cdsClAuxClone.EOF do
		begin
			if cdsClAuxClone.RecordCount=1 then
			begin
				cad:=cad+' CLAUXID='+QuotedStr(cdsClAuxClone.FieldByName('CLAUXID').AsString);
			end
			else
			begin
				if cdsClAuxClone.RecordCount>1 then
				begin
					if cdsClAuxClone.RecNo=cdsClAuxClone.RecordCount then
						cad:=cad+' CLAUXID='+QuotedStr(cdsClAuxClone.FieldByName('CLAUXID').AsString)
					else
						cad:=cad+' CLAUXID='+QuotedStr(cdsClAuxClone.FieldByName('CLAUXID').AsString)+' OR ';
				end;
			end;
			cdsClAuxClone.Next;
		end;
		if Length(cad)>0 then
			cad:='('+cad+')';
  end;
	cdsAux.Close;
	cdsAux.RemoteServer := DMCXP.DCOM1 ;
	cdsAux.ProviderName := 'dspTGE';

	if Length(cad)>0 then
		xSQL:=' SELECT PROV,PROVRUC,PROVDES,''N'' FLAG FROM TGE201 WHERE '+cad
	else
		xSQL:=' SELECT PROV,PROVRUC,PROVDES,''N'' FLAG FROM TGE201 ';



	cdsAux.DataRequest(xSQL);
	cdsAux.Open;
	cdsAux.IndexFieldNames:='PROV';

	dbgAux.Selected.Clear;
	dbgAux.Selected.Add('PROV'#9'15'#9'Id'#9'F');
	dbgAux.Selected.Add('PROVRUC'#9'15'#9'RUC'#9'F');
	dbgAux.Selected.Add('PROVDES'#9'28'#9'Razón Social'#9'F');
	dbgAux.RedrawGrid;

	cdsAuxClone.CloneCursor(cdsAux,TRUE) ;
	cdsAuxClone.FILTER := 'FLAG = ''S''' ;
	cdsAuxClone.FILTERED := True ;
	dbgAuxSelec.Selected.Clear;
	dbgAuxSelec.Selected.Add('PROV'#9'15'#9'Id'#9'F');
	dbgAuxSelec.Selected.Add('PROVRUC'#9'15'#9'RUC'#9'F');
	dbgAuxSelec.Selected.Add('PROVDES'#9'28'#9'Razón Social'#9'F');
	dbgAuxSelec.RedrawGrid;
	FCuadroMensual.Width:=635;
	Centra;
	Screen.Cursor:=crDefault;
end;

procedure TFCuadroMensual.dbgAuxDragOver(Sender, Source: TObject; X,
	Y: Integer; State: TDragState; var Accept: Boolean);
begin
	 Accept:=True;
end;

procedure TFCuadroMensual.dbgAuxEndDrag(Sender, Target: TObject; X,
  Y: Integer);
var i:integer;
begin
	 If (Target = dbgAuxSelec) AND (cdsAux.recordcount <> 0 ) Then
	 begin
			if dbgAux.SelectedList.Count>0 then
			begin
				 for i:= 0 to dbgAux.SelectedList.Count-1 do
				 begin
							dbgAux.datasource.dataset.GotoBookmark(dbgAux.SelectedList.items[i]);
							cdsAux.edit ;
							cdsAux.FieldByName('FLAG').AsString := 'S' ;
							cdsAux.Post ;
							dbgAux.datasource.dataset.Freebookmark(dbgAux.SelectedList.items[i]);
				 end; // for
				 dbgAux.SelectedList.clear;  { Clear selected record list since they are all deleted}
			end
			else
			begin
				 cdsAux.edit ;
				 cdsAux.FieldByName('FLAG').AsString := 'S' ;
				 cdsAux.Post ;
			end;
	 end ;
end;

procedure TFCuadroMensual.dbgAuxMouseDown(Sender: TObject;
  Button: TMouseButton; Shift: TShiftState; X, Y: Integer);
begin
	 dbgAux.BeginDrag(False);
end;

procedure TFCuadroMensual.dbgAuxSelecMouseDown(Sender: TObject;
  Button: TMouseButton; Shift: TShiftState; X, Y: Integer);
begin
  dbgAuxSelec.BeginDrag(False);
end;

procedure TFCuadroMensual.dbgAuxSelecDragOver(Sender, Source: TObject; X,
  Y: Integer; State: TDragState; var Accept: Boolean);
begin
	 Accept:=True;
end;

procedure TFCuadroMensual.dbgAuxTitleButtonClick(Sender: TObject;
  AFieldName: String);
begin
	 if AFieldName='CLAUXID'  then lblBusca1.Caption:='Clase de Auxiliar:';
	 if AFieldName='CLAUXDES' then lblBusca1.Caption:='Nombre de Clase de Auxiliar:';
	 cdsAux.indexfieldNames:= AFieldName;
	 isBusca.SearchField:= AFieldName;
	 isBusca.Left := lblBusca.Width+24;
	 pnlBusca1.Width:= 12+lblBusca1.Width+12+isBusca1.Width+12;
	 pnlBusca1.Visible := True;
	 isBusca1.SetFocus;
end;

procedure TFCuadroMensual.Centra;
Var
	I : Integer;
Begin
	With  Screen do
		 for I := 0 to FormCount-1 do
			 Begin
				 Forms[i].Top:=trunc((Height/2)-(Forms[0].Height/2));
				 Forms[i].Left:=Trunc((Width/2)-(Forms[0].Width/2));
				end;
end;

procedure TFCuadroMensual.isBusca1Exit(Sender: TObject);
begin
		pnlBusca1.visible:=False;
  dbgAux.SetFocus;		
end;

procedure TFCuadroMensual.isBuscaExit(Sender: TObject);
begin
		pnlBusca.visible:=False;
		dbgClAux.SetFocus;
end;

procedure TFCuadroMensual.dbgAuxSelecEndDrag(Sender, Target: TObject; X,
  Y: Integer);
var i:integer;
begin
	 If (Target = dbgAux) AND (cdsAuxClone.recordcount <> 0 ) Then
	 begin
			if dbgAuxSelec.SelectedList.Count>0 then
			begin
				 for i:= 0 to dbgAuxSelec.SelectedList.Count-1 do
				 begin
							dbgAuxSelec.datasource.dataset.GotoBookmark(dbgAuxSelec.SelectedList.items[i]);
							cdsAuxClone.edit ;
							cdsAuxClone.FieldByName('FLAG').AsString := 'N' ;
							cdsAuxClone.Post ;
							dbgAuxSelec.datasource.dataset.Freebookmark(dbgAuxSelec.SelectedList.items[i]);
				 end; // for
				 dbgAuxSelec.SelectedList.clear;  { Clear selected record list since they are all deleted}
			end
			else
			begin
				 cdsAuxClone.edit ;
				 cdsAuxClone.FieldByName('FLAG').AsString := 'N' ;
				 cdsAuxClone.Post ;
			end;
	 end ;
end;

procedure TFCuadroMensual.dbgClAuxSelecEndDrag(Sender, Target: TObject; X,
  Y: Integer);
var i:integer;
begin
	 If (Target = dbgClAux) AND (cdsClAuxClone.recordcount <> 0 ) Then
	 begin
			if dbgClAuxSelec.SelectedList.Count>0 then
			begin
				 for i:= 0 to dbgClAuxSelec.SelectedList.Count-1 do
				 begin
							dbgClAuxSelec.datasource.dataset.GotoBookmark(dbgClAuxSelec.SelectedList.items[i]);
							cdsClAuxClone.edit ;
							cdsClAuxClone.FieldByName('FLAG').AsString := 'N' ;
							cdsClAuxClone.Post ;
							dbgClAuxSelec.datasource.dataset.Freebookmark(dbgClAuxSelec.SelectedList.items[i]);
				 end; // for
				 dbgClAuxSelec.SelectedList.clear;  { Clear selected record list since they are all deleted}
			end
			else
			begin
				 cdsClAuxClone.edit ;
				 cdsClAuxClone.FieldByName('FLAG').AsString := 'N' ;
				 cdsClAuxClone.Post ;
			end;
	 end ;
end;

procedure TFCuadroMensual.FormClose(Sender: TObject;
  var Action: TCloseAction);
begin
   DMCXP.cdsReporte.Filter:='';
   DMCXP.cdsReporte.Filtered:=False;
   DMCXP.cdsReporte.IndexFieldNames:='';
   FVariables.w_Num_Formas :=FVariables.w_Num_Formas-1;
   Action:=caFree;
end;

procedure TFCuadroMensual.FormCreate(Sender: TObject);
begin

   CargaDataSource;

end;

procedure TFCuadroMensual.CargaDataSource;
begin
   dblcCia.DataSource        :=nil;
   dblcCia.LookupTable       :=DMCXP.cdsCia;
end;


end.
